<?php

/**
 * Created by PhpStorm.
 * User: HP ELITEBOOK 840 G5
 * Date: 5/26/2022
 * Time: 12:54 AM
 */

namespace app\modules\apiV1\controllers;


use app\models\Documents;
use app\modules\apiV1\resources\DocumentResource;
use yii\base\DynamicModel;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBearerAuth;
use yii\filters\Cors;
use yii\rest\ActiveController;

class DocumentController extends ActiveController
{
    public $modelClass = DocumentResource::class;

    public function behaviors()
    {
        $behaviours =  parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviours['cors'] = [
            'class' => Cors::class,
            'cors' => [
                // restrict access to
                //'Origin' => ['*'],
                //  methods to allow
                'Access-Control-Request-Method' => ['POST', 'PUT', 'GET'],
                // Allow only headers 'X-Wsse'
                'Access-Control-Request-Headers' => ['*'],
                // Allow credentials (cookies, authorization headers, etc.) to be exposed to the browser
                'Access-Control-Allow-Credentials' => false,
                // Allow OPTIONS caching
                'Access-Control-Max-Age' => 3600,
                // Allow the X-Pagination-Current-Page header to be exposed to the browser.
                'Access-Control-Expose-Headers' => ['X-Pagination-Current-Page'],
            ],
        ];

        /* $behaviours['authenticator']['only'] = ['view', 'create', 'update', 'delete'];
        $behaviours['authenticator']['authMethods'] = [
            HttpBearerAuth::class
        ];

        $behaviours['authenticator']['except'] = ['options'];*/

        return $behaviours;
    }

    public function actions()
    {
        $actions = parent::actions();
        $actions['index']['dataFilter'] = [
            'class' => \yii\data\ActiveDataFilter::class,
            'attributeMap' => [
                'agent' => 'created_by'
            ],
            'searchModel' => (new DynamicModel(['agent']))
                ->addRule(['agent'], 'integer', ['min' => 1])
        ];

        return $actions;
    }

    /* public function actions()
    {
        $actions = parent::actions();
        //redefine the prepareDataProvider variable of index action in ActiveController  class
        $actions['index']['prepareDataProvider'] = [$this, 'prepareDataProviderCB'];
        return $actions;
    }

    public function prepareDataProviderCB()
    {
        return new ActiveDataProvider([
            'query' => $this->modelClass::find()->andWhere(['created_by' => \Yii::$app->user->id])
        ]);
    }*/

    protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD'],
            'view' => ['GET', 'HEAD'],
            'create' => ['POST'],
            'update' => ['PUT', 'PATCH'],
            'delete' => ['DELETE'],
            'weekly-sales' => ['GET']
        ];
    }
}
