<?php

/**
 * Created by PhpStorm.
 * User: HP ELITEBOOK 840 G5
 * Date: 5/26/2022
 * Time: 12:54 AM
 */

namespace app\modules\apiV1\controllers;


use app\models\Candidate;
use app\models\PollingCenter;
use yii\base\DynamicModel;
use yii\filters\Cors;
use yii\rest\ActiveController;

class PollingStationController extends ActiveController
{
    public $modelClass = PollingCenter::class;

    public function behaviors()
    {
        $behaviours =  parent::behaviors(); // TODO: Change the autogenerated stub

        $behaviours['cors'] = [
            'class' => Cors::class,
            'cors' => [
                // restrict access to
                //'Origin' => ['*'],
                //  methods to allow
                'Access-Control-Request-Method' => ['POST', 'PUT', 'GET'],
                // Allow only headers 'X-Wsse'
                'Access-Control-Request-Headers' => ['*'],
                // Allow credentials (cookies, authorization headers, etc.) to be exposed to the browser
                'Access-Control-Allow-Credentials' => false,
                // Allow OPTIONS caching
                'Access-Control-Max-Age' => 3600,
                // Allow the X-Pagination-Current-Page header to be exposed to the browser.
                'Access-Control-Expose-Headers' => ['X-Pagination-Current-Page'],
            ],
        ];

        return $behaviours;
    }


    public function actions()
    {
        $actions = parent::actions();
        $actions['index']['dataFilter'] = [
            'class' => \yii\data\ActiveDataFilter::class,
            'attributeMap' => [
                'polling_station_code' => 'polling_station_code',

            ],
            'searchModel' => (new DynamicModel(['polling_station_code']))
                ->addRule(['polling_station_code'], 'integer', ['min' => 1])

        ];

        return $actions;
    }

    protected function verbs()
    {
        return [
            'index' => ['GET', 'HEAD'],
            'view' => ['GET', 'HEAD'],
            'create' => ['POST'],
            'update' => ['PUT', 'PATCH'],
            'delete' => ['DELETE'],
            'weekly-sales' => ['GET']
        ];
    }
}
